# Generated by Django 5.2.3 on 2025-07-02 07:51

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
