# Generated by Django 5.2.3 on 2025-07-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
